# Generated by Django 5.0.6 on 2024-12-01 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
    ]
